# Site settings
title: Bicycle and Dimed
email: adamnate@gmail.com
description: On (Not) Getting By on the Right in America.
url: "http://timesize.site" # the base hostname & protocol for your site
twitter_username: timesize
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Nathan Lee
      layout: "post"
      catagory: conferences
      comments: true

  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:

      layout: "page"

# Gems
gems: [jekyll-paginate]
